spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    # driver-class-name:  # org.h2.Driver
    url: jdbc:mysql://localhost:3306/bdd_geststages # jdbc:h2:mem:gepusoafdb
    username: usergs
    password: mdpGS
server:
  #servlet:
  #  context-path: /api
  error:
    include-stacktrace: always