spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    # driver-class-name:  # org.h2.Driver
    url: jdbc:mysql://eu-cdbr-west-02.cleardb.net/heroku_d86512ed837030d # jdbc:mysql://localhost:3306/bdd_geststages
    username: b718859d166ca8 # usergs
    password: 90682b3c # mdpGS
server:
  servlet:
    context-path: /api
  error:
    include-stacktrace: always