spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/bdd_geststages # jdbc:mysql://eu-cdbr-west-02.cleardb.net/heroku_d86512ed837030d
    username: usergs # b718859d166ca8
    password: mdpGS # 90682b3c
server:
  servlet:
    context-path: /api
  error:
    include-stacktrace: always